name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g turbo
      - run: npm install
      - run: turbo run build
      - run: turbo run test

  deploy-web:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/web


  deploy-worker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/llms-worker ./apps/worker
        gcloud run deploy llms-worker \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/llms-worker \
        --platform managed \
        --region ${{ secrets.GCP_REGION }} \
        --allow-unauthenticated